### ISSUE TITLE
涩图能正常转发，磁力风控，有没有办法规避

### ISSUE THREAD

**Issue by likingsdee** [half-ghost/bt_search#2]
![image](https://user-images.githubusercontent.com/37286077/142595866-70073ff8-84ac-4e06-9afb-cf4ac2bffa4a.png)
![image](https://user-images.githubusercontent.com/37286077/142595903-fbf6a26c-cc60-4047-8c62-7da4d1132f4f.png)

**Comment by half-ghost** [comment]
这个最近tx好像在抽风，大部分的合并消息都会被风控掉。可以规避，做法就是做成普通消息发送，但是因为消息量大，所以会造成刷屏，你考虑一下

**Comment by likingsdee** [comment]
好的，我下班了回去看看
