### ISSUE TITLE
似乎又搜不到结果了

### ISSUE THREAD

**Issue by 1055169799** [half-ghost/bt_search#4]
是不是搜索引擎挂了，要改了

**Comment by half-ghost** [comment]
> 是不是搜索引擎挂了，要改了

实际上已经好久没更新这插件的引擎了(
我找时间更新一下吧

**Comment by half-ghost** [comment]
已修复，去除了一个已经炸了的引擎。目前只有3个

**Comment by 1055169799** [comment]
> 已修复，去除了一个已经炸了的引擎。目前只有3个

好的
